Repository edgexfoundry/edgex-compose, pull requests merged in 2021-04, with the labels that each got.

#41 feat(security): Update consul's volume on secrets folder to be writable
  compose-builder/add-security.yml
  releases/pre-release/docker-compose-pre-release-arm64.yml
  releases/pre-release/docker-compose-pre-release.yml
  releases/pre-release/taf/docker-compose-taf-arm64.yml
  releases/pre-release/taf/docker-compose-taf-perf-arm64.yml
  releases/pre-release/taf/docker-compose-taf-perf.yml
  releases/pre-release/taf/docker-compose-taf.yml
Labels: 3-high, ireland, security-services

#63 feat(security): Integrate device services with consul tokens
  compose-builder/.gitignore
  compose-builder/Makefile
  compose-builder/README.md
  compose-builder/add-asc-mqtt-export-secure.yml
  compose-builder/add-service-secure-template.yml
  compose-builder/gen_secure_compose_ext.sh
  docker-compose-pre-release-arm64.yml
  docker-compose-pre-release.yml
  taf/docker-compose-taf-arm64.yml
  taf/docker-compose-taf-perf-arm64.yml
  taf/docker-compose-taf-perf.yml
  taf/docker-compose-taf.yml
Labels: device-services, enhancement, ireland, security-services

#65 fix(security): Fix TAF failing to start device-virtual
  compose-builder/Makefile
  taf/docker-compose-taf-arm64.yml
  taf/docker-compose-taf.yml
Labels: 3-high, bug, device-services, ireland

#67 docs: Add badges to readme
  README.md
Labels: documentation
