Repository edgexfoundry/edgex-compose, pull requests merged in 2023-03, with the labels that each got.

#349 fix: Eliminate unnamed Kuiper volumes
  compose-builder/docker-compose-base.yml
Labels: tech-debt

#353 fix: Remove forcing common-config-bootstrap no security
  compose-builder/docker-compose-base.yml
  docker-compose-arm64.yml
  docker-compose-no-secty-arm64.yml
  docker-compose-no-secty-with-app-sample-arm64.yml
  docker-compose-no-secty-with-app-sample.yml
  docker-compose-no-secty.yml
  docker-compose-with-app-sample-arm64.yml
  docker-compose-with-app-sample.yml
  docker-compose.yml
  taf/docker-compose-taf-arm64.yml
  taf/docker-compose-taf-mqtt-bus-arm64.yml
  taf/docker-compose-taf-mqtt-bus.yml
  taf/docker-compose-taf-no-secty-arm64.yml
  taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
  taf/docker-compose-taf-no-secty-mqtt-bus.yml
  taf/docker-compose-taf-no-secty.yml
  taf/docker-compose-taf-perf-arm64.yml
  taf/docker-compose-taf-perf-no-secty-arm64.yml
  taf/docker-compose-taf-perf-no-secty.yml
  taf/docker-compose-taf-perf.yml
  taf/docker-compose-taf.yml
Labels: bug

#350 fix: Enable new proxy-auth service to register in service registry
  compose-builder/add-security.yml
  docker-compose-arm64.yml
  docker-compose-with-app-sample-arm64.yml
  docker-compose-with-app-sample.yml
  docker-compose.yml
  taf/docker-compose-taf-arm64.yml
  taf/docker-compose-taf-mqtt-bus-arm64.yml
  taf/docker-compose-taf-mqtt-bus.yml
  taf/docker-compose-taf-perf-arm64.yml
  taf/docker-compose-taf-perf.yml
  taf/docker-compose-taf.yml
Labels: bug, security-services

#355 refactor: Rework env overrides for common config in place
  compose-builder/Makefile
  compose-builder/README.md
  compose-builder/add-app-rfid-llrp-inventory.yml
  compose-builder/add-asc-external-mqtt-trigger.yml
  compose-builder/add-asc-http-export.yml
  compose-builder/add-asc-metrics-influxdb.yml
  compose-builder/add-asc-mqtt-export.yml
  compose-builder/add-asc-sample.yml
  compose-builder/add-delayed-start-services.yml
  compose-builder/add-device-bacnet.yml
  compose-builder/add-device-coap.yml
  compose-builder/add-device-gpio.yml
  compose-builder/add-device-modbus.yml
  compose-builder/add-device-mqtt.yml
  compose-builder/add-device-onvif-camera.yml
  compose-builder/add-device-rest.yml
  compose-builder/add-device-rfid-llrp.yml
  compose-builder/add-device-snmp.yml
  compose-builder/add-device-usb-camera.yml
  compose-builder/add-device-virtual.yml
  compose-builder/add-mqtt-messagebus-app-template.yml
  compose-builder/add-mqtt-messagebus-device-template.yml
  compose-builder/add-mqtt-messagebus.yml
  compose-builder/add-nats-messagebus-app-template.yml
  compose-builder/add-nats-messagebus-device-template.yml
  compose-builder/add-nats-messagebus.yml
  compose-builder/add-secure-mqtt-messagebus.yml
  compose-builder/add-secure-redis-messagebus.yml
  compose-builder/add-security.yml
  compose-builder/add-taf-app-services.yml
  compose-builder/as-common.env
  compose-builder/asc-http-export.env
  compose-builder/common-non-security.env
  compose-builder/common.env
  compose-builder/device-common.env
  compose-builder/docker-compose-base.yml
  compose-builder/gen_mqtt_messagebus_compose_ext.sh
  compose-builder/gen_nats_messagebus_compose_ext.sh
  compose-builder/mqtt-bus.env
  compose-builder/nats-bus.env
  docker-compose-arm64.yml
  docker-compose-no-secty-arm64.yml
  docker-compose-no-secty-with-app-sample-arm64.yml
  docker-compose-no-secty-with-app-sample.yml
  docker-compose-no-secty.yml
  docker-compose-with-app-sample-arm64.yml
  docker-compose-with-app-sample.yml
  docker-compose.yml
  taf/docker-compose-taf-arm64.yml
  taf/docker-compose-taf-mqtt-bus-arm64.yml
  taf/docker-compose-taf-mqtt-bus.yml
  taf/docker-compose-taf-no-secty-arm64.yml
  taf/docker-compose-taf-no-secty-mqtt-bus-arm64.yml
  taf/docker-compose-taf-no-secty-mqtt-bus.yml
  taf/docker-compose-taf-no-secty.yml
  taf/docker-compose-taf-perf-arm64.yml
  taf/docker-compose-taf-perf-no-secty-arm64.yml
  taf/docker-compose-taf-perf-no-secty.yml
  taf/docker-compose-taf-perf.yml
  taf/docker-compose-taf.yml
Labels: tech-debt
